name: Pull Request

on:
  pull_request: {}

jobs:
  build:
    name: Check commit message
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - name: Validate commit messages of this branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cz check --rev-range origin/main..$(git rev-parse HEAD)

      - name: Validate pull request title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cz check --message ${{ github.event.pull_request.title }}
