name: Release version

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  release-version:
    if: "!startsWith(github.event.head_commit.message, 'rel:')"
    runs-on: ubuntu-latest
    name: "Bump version, create changelog and release"

    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
#          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build package
        run: |
          python -m build

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
#          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
